---
- name: Testing andrewrothstein.kpack
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'kp version'
      ansible.builtin.command: kp version
      changed_when: false
      register: kp_test_output
    - name: Output of 'kp version'
      debug:
        msg: '{{ kp_test_output.stdout }}'
